using System;
using System.Collections.Generic;
using UnityEngine;

namespace LanternKeeper
{
public enum SoundGroup { Music, Sfx, Ambience, UI }

public enum SynthFallback
{
    None, Chime, FireflyArrive, Beacon, Whoomp, Footstep, Splash, Fizzle, Crackle, Dying, Heartbeat,
    MothFlutter, MothWhisper, ShadeDrone, Ambience, Surf, WindBed, WindHowl, Rain, ThunderRumble, ThunderCrack
}

[Serializable]
public class SoundCue
{
    public string name;
    public AudioClip[] clips = new AudioClip[0];
    public float volume = 1f;
    public Vector2 pitch = Vector2.one;
    public float volumeJitterDb;
    public SoundGroup group = SoundGroup.Sfx;
    public bool spatial;
    public float minDistance = 1f;
    public float maxDistance = 500f;
    public AudioRolloffMode rolloff = AudioRolloffMode.Logarithmic;
    public bool priority;
    public SynthFallback fallback;
}

// Every named sound cue. Generated by Lantern Keeper > Build Sound Bank from the cue table and the files in Assets/Game/Audio.
public class SoundBank : ScriptableObject
{
    [SerializeField] private List<SoundCue> cues = new List<SoundCue>();

    public IReadOnlyList<SoundCue> Cues { get { return cues; } }

    public SoundCue Find(string cueName)
    {
        for (int i = 0; i < cues.Count; i++)
        {
            if (cues[i].name == cueName)
            {
                return cues[i];
            }
        }

        return null;
    }

    public void SetCues(List<SoundCue> list)
    {
        cues = list;
    }
}
}
