schema_version = "1.0.0"
id = "water_shader_addon_free"
version = "2.1.2"
name = "Water_Shader_Addon_Free"
tagline = "Water shader material for blender"
maintainer = "chuck cg"
type = "add-on"
tags = ["Material"]
blender_version_min = "3.6.0"
license = [
"SPDX:GPL-2.0-or-later",
]